### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by kiliankoe**
Test coverage is at 67.7%. Not covered: Arguments(), NormalizedArguments(), Print() in response.go.

All tests currently pass, although I'm unsure about the expected result on the [first response test](https://github.com/BenchR267/goalfred/compare/master...kiliankoe:master#diff-8d95f6e0d01c8a50dc3661994ba7cb12R16).

I also renamed complex_arg.go to complexarg.go going with go conventions.

### CODE REVIEW

**Comment by kiliankoe** [comment]
Looks like the normalizing test failed on travis. I'm guessing because iconv isn't available? 😕 

Building this on an OS X image might be an option, but [Travis states](https://docs.travis-ci.com/user/osx-ci-environment/) that only go 1.3.1 is available there? But why not install a newer version manually via homebrew? 😄 
Or check how to install iconv on the current machine? Or details as to how to use it if it's already there?

**Comment by BenchR267** [comment]
Hm, I think iconv itself is available, but the encoding might not :/

**Comment by kiliankoe** [comment]
Oh yeah, that might also be the case...

**Comment by kiliankoe** [comment]
🎉

**Comment by BenchR267** [comment]
Awesome, thank you very much!

**Pull request merged**
